# Eflux2 applied to *A. niger*

In [42]:
import sys
import pandas as pd
import cobra
sys.path.append('../../src')
from eflux2 import EFlux2

## Read global proteomics normalized to the reference strain SF ABF180_17_R2

[(βAl-3HP)++, pyc2++, Δald6a+NeoR] (Strain ABF-10216R8, ICE ID ABF_011245)

In [43]:
global_prot = pd.read_csv('../../data/round2/normalized_global_proteomics.csv', index_col='Transcript')
global_prot

,SF ABF180_1_R1,SF ABF180_1_R2,SF ABF180_1_R3,SF ABF180_2_R1,SF ABF180_2_R2,SF ABF180_2_R3,SF ABF180_3_R1,SF ABF180_3_R2,SF ABF180_3_R3,SF ABF180_4_R1,...,SF ABF180_21_R3,SF ABF180_22_R1,SF ABF180_22_R2,SF ABF180_22_R3,SF ABF180_23_R1,SF ABF180_23_R2,SF ABF180_23_R3,SF ABF180_24_R1,SF ABF180_24_R2,SF ABF180_24_R3
Transcript,,,,,,,,,,,,,,,,,,,,,
1170085,0.967266,0.996633,0.992893,0.988900,1.005546,0.994246,0.995436,0.984235,0.985065,0.987202,...,0.996191,1.000241,0.981752,1.003174,1.000581,1.006389,0.998983,0.974427,0.986005,0.982189
1141495,1.012991,1.010041,1.011290,1.012467,1.008045,1.010177,1.032464,1.009299,1.012114,1.014553,...,1.010923,1.019918,1.003567,1.020978,1.010532,1.022859,1.026123,1.015454,1.016219,1.003530
201546,0.979618,0.980405,0.973220,0.981140,0.998126,0.998079,0.991908,0.981119,0.990187,0.990484,...,0.988765,0.994606,0.979760,0.993260,1.001902,0.996684,0.994010,0.982122,0.986781,0.980817
1147898,0.995988,1.000736,0.999673,1.021090,1.020466,1.023879,1.007351,1.005843,1.003600,1.006999,...,1.007180,1.001447,1.008006,1.004574,1.003261,1.014986,1.022990,1.002505,0.996382,1.002931
1142869,1.018378,1.017542,1.017273,1.015201,1.009343,1.003975,1.016892,1.010228,1.026211,1.010030,...,1.000423,1.002124,1.005939,1.004112,1.001554,1.010091,0.992440,1.000478,0.998578,0.997856
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117615,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
210213,1.000000,1.000000,1.000000,1.000000,1.000000,0.926492,0.928163,1.000000,0.951025,1.000000,...,1.013350,1.024441,1.026118,1.015304,1.012428,0.997734,0.990888,0.970595,1.000000,0.954842
1119048,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1128143,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
197079,1.021560,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.001600,...,1.000932,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.005890

## Read iJB1325 with non-native genes added for 3HP production

In [44]:
# todo: update gurobi license (not required to use gurobi)
model = cobra.io.load_json_model('../../models/iJB1325_HP.json')
#model.solver = 'gurobi'
#model.solver

In [45]:
model.medium

{'BOUNDARY_GLCe': 10.0,
 'BOUNDARY_H2Oe': 1000.0,
 'BOUNDARY_HNO3e': 1000.0,
 'BOUNDARY_O2e': 1000.0,
 'BOUNDARY_PIe': 1000.0,
 'BOUNDARY_SLFe': 1000.0,
 'BOUNDARY_Ke': 1000.0,
 'BOUNDARY_CAe': 1000.0}

In [46]:
model.reactions.BOUNDARY_HNO3e.lower_bound = 0.0
model.reactions.BOUNDARY_NH4e.lower_bound = -1000.0

## Read line rates

In [48]:
line_rates = pd.read_csv('../../data/round2/Line_rates.csv', index_col='Line Name')
line_rates.head()

,Omics Sample ID,Strain (ICE),Genotype,GLCe (mmol/gDW/hr),3hpp_e (mmol/gDW/hr),ETHe (mmol/gDW/hr),EOLe (mmol/gDW/hr),CITe (mmol/gDW/hr)
Line Name,,,,,,,,
SF ABF180_1_R1,SF ABF180_1_R1,ABF_008340,wild-type,-3.824936,0.000000,-0.792609,0.003407,0.013740
SF ABF180_1_R2,SF ABF180_1_R2,ABF_008340,wild-type,-3.557249,0.000000,-0.678005,0.012109,0.009979
SF ABF180_1_R3,SF ABF180_1_R3,ABF_008340,wild-type,-3.415471,0.000000,-1.080524,0.010234,0.009554
SF ABF180_2_R1,SF ABF180_2_R1,ABF_008343,(βAl-3HP)+,-5.928543,2.040397,-0.352736,0.022628,-0.001312
SF ABF180_2_R2,SF ABF180_2_R2,ABF_008343,(βAl-3HP)+,-5.792077,2.099299,-0.539260,0.005308,-0.002935

In [49]:
# Drop ethanol uptake - this is likely evaporation
line_rates = line_rates.drop(columns='ETHe (mmol/gDW/hr)')

## Normalize uptake and secretion rates by glucose uptake rate of reference study line.

In [50]:
ref_line = 'SF ABF180_17_R2'

ref_line_glucose_rate = -line_rates.loc[ref_line,'GLCe (mmol/gDW/hr)']
ref_line_glucose_rate

6.277127634711532

In [51]:
normalized_line_rates = line_rates.drop(['Omics Sample ID', 'Strain (ICE)', 'Genotype'], axis=1)
normalized_line_rates = normalized_line_rates.divide(ref_line_glucose_rate, axis=1)
normalized_line_rates

,GLCe (mmol/gDW/hr),3hpp_e (mmol/gDW/hr),EOLe (mmol/gDW/hr),CITe (mmol/gDW/hr)
Line Name,,,,
SF ABF180_1_R1,-0.609345,0.000000,0.000543,0.002189
SF ABF180_1_R2,-0.566700,0.000000,0.001929,0.001590
SF ABF180_1_R3,-0.544114,0.000000,0.001630,0.001522
SF ABF180_2_R1,-0.944467,0.325053,0.003605,-0.000209
SF ABF180_2_R2,-0.922727,0.334436,0.000846,-0.000467
...,...,...,...,...
SF ABF180_23_R2,-0.989133,0.478907,0.012959,0.001360
SF ABF180_23_R3,-1.137562,0.564224,0.013712,0.001255
SF ABF180_24_R1,-1.124896,0.949444,0.024140,0.002688
SF ABF180_24_R2,-0.812758,0.704418,0.030635,0.002526
SF ABF180_24_R3,-1.040476,0.800213,0.020284,0.002560

In [52]:
normalized_line_rates[(normalized_line_rates < 0).any(axis=1)]

,GLCe (mmol/gDW/hr),3hpp_e (mmol/gDW/hr),EOLe (mmol/gDW/hr),CITe (mmol/gDW/hr)
Line Name,,,,
SF ABF180_1_R1,-0.609345,0.000000,0.000543,0.002189
SF ABF180_1_R2,-0.566700,0.000000,0.001929,0.001590
SF ABF180_1_R3,-0.544114,0.000000,0.001630,0.001522
SF ABF180_2_R1,-0.944467,0.325053,0.003605,-0.000209
SF ABF180_2_R2,-0.922727,0.334436,0.000846,-0.000467
...,...,...,...,...
SF ABF180_23_R2,-0.989133,0.478907,0.012959,0.001360
SF ABF180_23_R3,-1.137562,0.564224,0.013712,0.001255
SF ABF180_24_R1,-1.124896,0.949444,0.024140,0.002688
SF ABF180_24_R2,-0.812758,0.704418,0.030635,0.002526
SF ABF180_24_R3,-1.040476,0.800213,0.020284,0.002560

In [53]:
(normalized_line_rates < 0).any()

GLCe (mmol/gDW/hr)       True
3hpp_e (mmol/gDW/hr)    False
EOLe (mmol/gDW/hr)      False
CITe (mmol/gDW/hr)       True
dtype: bool

In [12]:
# Instead of replacing negative values with zero
# normalized_line_rates[normalized_line_rates < 0] = 0.0
# Use negative values for uptake and positive values for secretion

In [9]:
normalized_line_rates.to_csv('../../data/round2/normalized_line_rates.csv')

### Reduce the model based on the FBA solution maximizing CO2 production in the reference strain

In [55]:
const_dict = {
       'BOUNDARY_GLCe': 'GLCe (mmol/gDW/hr)',
       'EX_3hpp_e': '3hpp_e (mmol/gDW/hr)',
       #'BOUNDARY_ETHe': 'ETHe (mmol/gDW/hr)',
       'BOUNDARY_EOLe': 'EOLe (mmol/gDW/hr)',
       'BOUNDARY_CITe': 'CITe (mmol/gDW/hr)'
}

In [56]:
with model:
    for k, v in const_dict.items():
        model.reactions.get_by_id(k).lower_bound = normalized_line_rates[v][ref_line]
    model.objective = 'BOUNDARY_CO2e'
    pfba_sol_ref = cobra.flux_analysis.pfba(model)

In [62]:
len(pfba_sol_ref[abs(pfba_sol_ref.fluxes) > 1e-9])

93

In [64]:
zero_flux_ref = pfba_sol_ref[abs(pfba_sol_ref.fluxes) < 1e-9].index
model.remove_reactions(zero_flux_ref, remove_orphans=True)

In [65]:
model

## Run Eflux

In [66]:
fluxes = {}
for rep in global_prot.columns:
    with model:
        for k, v in const_dict.items():
            model.reactions.get_by_id(k).lower_bound = normalized_line_rates[v][rep]
        try:
            print(rep)
            fluxes[rep] = EFlux2(model, global_prot[rep])
        except TypeError:
            print(f"Replicate {rep} with glucose {glucose_uptake} and 3hp {secrete_3hp} is infeasible")

SF ABF180_1_R1
FBA status optimal
FBA solution 1.86287951370712
EFlux2 status optimal
EFlux2 solution 33.80125399895117
SF ABF180_1_R2
FBA status optimal
FBA solution 1.7308518612251667
EFlux2 status optimal
EFlux2 solution 29.15558791909489
SF ABF180_1_R3
FBA status optimal
FBA solution 1.662186123575238
EFlux2 status optimal
EFlux2 solution 26.891289857622816
SF ABF180_2_R1
FBA status optimal
FBA solution 2.288427035378078
EFlux2 status optimal
EFlux2 solution 59.37992661009217
SF ABF180_2_R2
FBA status optimal
FBA solution 2.2764924626531466
EFlux2 status optimal
EFlux2 solution 58.87997712102427
SF ABF180_2_R3
FBA status optimal
FBA solution 2.2735496876303514
EFlux2 status optimal
EFlux2 solution 58.78485731303181
SF ABF180_3_R1
FBA status optimal
FBA solution 2.2700681777641103
EFlux2 status optimal
EFlux2 solution 58.391931314291966
SF ABF180_3_R2
FBA status optimal
FBA solution 2.2792580739100132
EFlux2 status optimal
EFlux2 solution 58.721353168966225
SF ABF180_3_R3
FBA status optimal
FBA solution 2.2812570609795175
EFlux2 status optimal
EFlux2 solution 58.8534431229538
SF ABF180_4_R1
FBA status optimal
FBA solution 2.277071568460099
EFlux2 status optimal
EFlux2 solution 58.539203529908214
SF ABF180_4_R2
FBA status optimal
FBA solution 2.278141616951915
EFlux2 status optimal
EFlux2 solution 58.70155164439988
SF ABF180_4_R3
FBA status optimal
FBA solution 2.27537578867538
EFlux2 status optimal
EFlux2 solution 58.460652066193084
SF ABF180_5_R1
FBA status infeasible
FBA solution 0.0907009689142967

/Users/kimj972/anaconda3/envs/python3_cobrapy/lib/python3.6/site-packages/cobra/util/solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

EFlux2 status infeasible
EFlux2 solution 0.08721463752713277
SF ABF180_5_R2
FBA status infeasible
FBA solution 0.042408993134607144
EFlux2 status infeasible
EFlux2 solution 0.11638458967067322
SF ABF180_5_R3
FBA status infeasible
FBA solution 0.19086847792502332
EFlux2 status infeasible
EFlux2 solution 0.22181524514734008
SF ABF180_6_R1
FBA status optimal
FBA solution 2.101029843405702
EFlux2 status optimal
EFlux2 solution 45.88381911757923
SF ABF180_6_R2
FBA status optimal
FBA solution 2.2743700077984004
EFlux2 status optimal
EFlux2 solution 58.339048264111355
SF ABF180_6_R3
FBA status optimal
FBA solution 2.2644271793038455
EFlux2 status optimal
EFlux2 solution 58.02961252173907
SF ABF180_7_R1
FBA status optimal
FBA solution 2.213252360431179
EFlux2 status optimal
EFlux2 solution 52.83988667430047
SF ABF180_7_R2
FBA status optimal
FBA solution 2.265270856391254
EFlux2 status optimal
EFlux2 solution 58.14659228018724
SF ABF180_7_R3
FBA status optimal
FBA solution 2.2694028736714
EFlux2 status optimal
EFlux2 solution 58.312917848277806
SF ABF180_8_R1
FBA status optimal
FBA solution 2.277338344555701
EFlux2 status optimal
EFlux2 solution 58.564737421340276
SF ABF180_8_R2
FBA status optimal
FBA solution 2.1858910932160427
EFlux2 status optimal
EFlux2 solution 49.920428884924426
SF ABF180_8_R3
FBA status optimal
FBA solution 2.2695055552093084
EFlux2 status optimal
EFlux2 solution 58.29848776894293
SF ABF180_9_R1
FBA status optimal
FBA solution 2.2739777191594666
EFlux2 status optimal
EFlux2 solution 58.55816386007078
SF ABF180_9_R2
FBA status optimal
FBA solution 2.231198261822439
EFlux2 status optimal
EFlux2 solution 54.41750036313183
SF ABF180_9_R3
FBA status optimal
FBA solution 2.2766770784434867
EFlux2 status optimal
EFlux2 solution 58.72950580744667
SF ABF180_10_R1
FBA status optimal
FBA solution 2.2735982423693377
EFlux2 status optimal
EFlux2 solution 58.546887251758214
SF ABF180_10_R2
FBA status optimal
FBA solution 2.288594199947732
EFlux2 status optimal
EFlux2 solution 59.02914282806599
SF ABF180_10_R3
FBA status optimal
FBA solution 1.682037396556524
EFlux2 status optimal
EFlux2 solution 27.515594284478638
SF ABF180_11_R1
FBA status optimal
FBA solution 2.259610776798124
EFlux2 status optimal
EFlux2 solution 57.95718148494138
SF ABF180_11_R2
FBA status optimal
FBA solution 2.2825250432905526
EFlux2 status optimal
EFlux2 solution 58.619803522356584
SF ABF180_11_R3
FBA status optimal
FBA solution 2.286931121827099
EFlux2 status optimal
EFlux2 solution 58.833664208086
SF ABF180_12_R1
FBA status optimal
FBA solution 2.2829522938262814
EFlux2 status optimal
EFlux2 solution 58.59621237880106
SF ABF180_12_R2
FBA status optimal
FBA solution 2.280272800262604
EFlux2 status optimal
EFlux2 solution 58.654493577158824
SF ABF180_12_R3
FBA status optimal
FBA solution 2.290266974286906
EFlux2 status optimal
EFlux2 solution 59.022717206984495
SF ABF180_13_R1
FBA status optimal
FBA solution 2.277034952626157
EFlux2 status optimal
EFlux2 solution 58.74821408784225
SF ABF180_13_R2
FBA status optimal
FBA solution 2.2717709843656717
EFlux2 status optimal
EFlux2 solution 58.46516119828302
SF ABF180_13_R3
FBA status optimal
FBA solution 2.1254320270296985
EFlux2 status optimal
EFlux2 solution 53.708806542082776
SF ABF180_14_R1
FBA status optimal
FBA solution 2.277765854874266
EFlux2 status optimal
EFlux2 solution 58.56113468008363
SF ABF180_14_R2
FBA status optimal
FBA solution 2.2245428747593525
EFlux2 status optimal
EFlux2 solution 56.91217842974814
SF ABF180_14_R3
FBA status optimal
FBA solution 2.28308046115154
EFlux2 status optimal
EFlux2 solution 58.849355680199764
SF ABF180_15_R1
FBA status optimal
FBA solution 2.2737547803938183
EFlux2 status optimal
EFlux2 solution 58.512624661565305
SF ABF180_15_R2
FBA status optimal
FBA solution 2.2766850658356024
EFlux2 status optimal
EFlux2 solution 58.60580782396979
SF ABF180_15_R3
FBA status optimal
FBA solution 2.259027516800928
EFlux2 status optimal
EFlux2 solution 57.923923847256134
SF ABF180_16_R1
FBA status optimal
FBA solution 2.280871169850535
EFlux2 status optimal
EFlux2 solution 58.778440585741244
SF ABF180_16_R2
FBA status optimal
FBA solution 2.270041781864261
EFlux2 status optimal
EFlux2 solution 58.4064480865818
SF ABF180_16_R3
FBA status optimal
FBA solution 2.2783372598705043
EFlux2 status optimal
EFlux2 solution 58.62583278939088
SF ABF180_17_R1
FBA status infeasible
FBA solution 0.6748363229482861
EFlux2 status infeasible
EFlux2 solution 49.86008051935004
SF ABF180_17_R2
FBA status infeasible
FBA solution 1.1977415960250162
EFlux2 status infeasible
EFlux2 solution 58.58969411841859
SF ABF180_17_R3
FBA status infeasible
FBA solution 1.180927400538092
EFlux2 status infeasible
EFlux2 solution 58.44747267874714
SF ABF180_18_R1
FBA status infeasible
FBA solution 0.026366756438773647
EFlux2 status infeasible
EFlux2 solution 2.014733342108073
SF ABF180_18_R2
FBA status optimal
FBA solution 2.291045030693368
EFlux2 status optimal
EFlux2 solution 59.153486575110264
SF ABF180_18_R3
FBA status optimal
FBA solution 2.2899943475834696
EFlux2 status optimal
EFlux2 solution 59.10966079338257
SF ABF180_19_R1
FBA status infeasible
FBA solution 0.1025620520686189
EFlux2 status infeasible
EFlux2 solution 1.8685969538628626
SF ABF180_19_R2
FBA status optimal
FBA solution 2.2893617026540722
EFlux2 status optimal
EFlux2 solution 59.218815350061924
SF ABF180_19_R3
FBA status infeasible
FBA solution 0.3043775838032764
EFlux2 status infeasible
EFlux2 solution 43.959401319141115
SF ABF180_20_R1
FBA status infeasible
FBA solution 0.46187549194038935
EFlux2 status infeasible
EFlux2 solution 46.236461904441605
SF ABF180_20_R2
FBA status infeasible
FBA solution 0.14767557026936426
EFlux2 status infeasible
EFlux2 solution 0.9202378628229155
SF ABF180_20_R3
FBA status infeasible
FBA solution 0.0024037461918278748
EFlux2 status infeasible
EFlux2 solution 1.1186182009978864
SF ABF180_21_R1
FBA status infeasible
FBA solution 0.6568698362090429
EFlux2 status infeasible
EFlux2 solution 49.57403239495641
SF ABF180_21_R2
FBA status infeasible
FBA solution 0.17523101238682415
EFlux2 status infeasible
EFlux2 solution 1.2091711597534527
SF ABF180_21_R3
FBA status infeasible
FBA solution 0.9977535938830966
EFlux2 status infeasible
EFlux2 solution 55.258317729652376
SF ABF180_22_R1
FBA status infeasible
FBA solution 0.22023605703612986
EFlux2 status infeasible
EFlux2 solution 1.2886358419549708
SF ABF180_22_R2
FBA status infeasible
FBA solution 2.035252379893082
EFlux2 status infeasible
EFlux2 solution 63.694185570636925
SF ABF180_22_R3
FBA status infeasible
FBA solution 2.285447759890453
EFlux2 status infeasible
EFlux2 solution 68.93760508644593
SF ABF180_23_R1
FBA status optimal
FBA solution 2.2966317507246616
EFlux2 status optimal
EFlux2 solution 59.50486632756176
SF ABF180_23_R2
FBA status optimal
FBA solution 2.2973476826063113
EFlux2 status optimal
EFlux2 solution 59.651899514716526
SF ABF180_23_R3
FBA status optimal
FBA solution 2.282297617328355
EFlux2 status optimal
EFlux2 solution 58.99243157076252
SF ABF180_24_R1
FBA status optimal
FBA solution 2.2818936647178605
EFlux2 status optimal
EFlux2 solution 58.857578021015925
SF ABF180_24_R2
FBA status optimal
FBA solution 2.2058472163046154
EFlux2 status optimal
EFlux2 solution 51.65859687228904
SF ABF180_24_R3
FBA status optimal
FBA solution 2.283823035261687
EFlux2 status optimal
EFlux2 solution 58.82244166326472

In [67]:
for rep in global_prot.columns:
    if fluxes[rep].status is not 'optimal':
        print(rep, fluxes[rep].status)

SF ABF180_5_R1 infeasible
SF ABF180_5_R2 infeasible
SF ABF180_5_R3 infeasible
SF ABF180_17_R1 infeasible
SF ABF180_17_R2 infeasible
SF ABF180_17_R3 infeasible
SF ABF180_18_R1 infeasible
SF ABF180_19_R1 infeasible
SF ABF180_19_R3 infeasible
SF ABF180_20_R1 infeasible
SF ABF180_20_R2 infeasible
SF ABF180_20_R3 infeasible
SF ABF180_21_R1 infeasible
SF ABF180_21_R2 infeasible
SF ABF180_21_R3 infeasible
SF ABF180_22_R1 infeasible
SF ABF180_22_R2 infeasible
SF ABF180_22_R3 infeasible

### get eflux2 solutions by adding slack variables for infeasible cases

In [23]:
import numpy as np
from optlang.symbolics import add
from eflux2 import get_eflux2_bounds
from eflux.eflux2 import add_slack_variables_to_model

In [28]:
for rep in global_prot.columns:
    if fluxes[rep].status is not 'optimal':
        print(rep)
        # get eflux2 bounds from global proteomics
        eflux2_bounds = get_eflux2_bounds(model, global_prot[rep])
        upper_bounds = {k: v[1] if v[1] <= 1000.0 else 1000.0 for k, v in eflux2_bounds.items()}
        # build a relaxed model with slack variables
        relaxed_model = add_slack_variables_to_model(model, upper_bounds)
        # solve FBA to calculate the maximum CO2
        relaxed_model.tolerance = 1e-9
        fba_sol = relaxed_model.optimize()
        print('FBA status', fba_sol.status)
        print('FBA solution', fba_sol.objective_value)
        # Constrain the growth to the optimal value
        for r in relaxed_model.reactions:
            if r.objective_coefficient == 1.0:
                r.lower_bound = fba_sol[r.id]
        # minimize the sum of squared flux values
        relaxed_model.objective = relaxed_model.problem.Objective(add([r.flux_expression**2 for r in relaxed_model.reactions]), direction='min')
        eflux2_sol = relaxed_model.optimize()
        print('EFlux2 status', eflux2_sol.status)
        print('EFlux2 solution', eflux2_sol.objective_value)
        fluxes[rep] = eflux2_sol

SF ABF180_5_R1
FBA status optimal
FBA solution 0.0
EFlux2 status optimal
EFlux2 solution 4.9093324742347827e-11
SF ABF180_5_R2
FBA status optimal
FBA solution 0.0
EFlux2 status optimal
EFlux2 solution 4.736805118201147e-11
SF ABF180_5_R3
FBA status optimal
FBA solution 0.0
EFlux2 status optimal
EFlux2 solution -1.1967845666940655e-09
SF ABF180_17_R1
FBA status optimal
FBA solution 0.0
EFlux2 status optimal
EFlux2 solution -2.5123421961024682e-11
SF ABF180_17_R2
FBA status optimal
FBA solution 0.0
EFlux2 status optimal
EFlux2 solution -1.0824451831230847e-09
SF ABF180_17_R3
FBA status optimal
FBA solution 0.0
EFlux2 status optimal
EFlux2 solution -2.133435419890147e-09
SF ABF180_19_R1
FBA status optimal
FBA solution 0.0
EFlux2 status optimal
EFlux2 solution -1.2644389707123762e-10
SF ABF180_19_R3
FBA status optimal
FBA solution 0.0
EFlux2 status optimal
EFlux2 solution -5.020976105324271e-10
SF ABF180_20_R1
FBA status optimal
FBA solution 0.0
EFlux2 status optimal
EFlux2 solution -1.7372255077045817e-09
SF ABF180_20_R2
FBA status optimal
FBA solution 0.0
EFlux2 status optimal
EFlux2 solution -8.567713121359276e-10
SF ABF180_21_R1
FBA status optimal
FBA solution 0.0
EFlux2 status optimal
EFlux2 solution -2.1789531655405305e-11
SF ABF180_21_R2
FBA status optimal
FBA solution 0.0
EFlux2 status optimal
EFlux2 solution -1.2862197421537537e-10
SF ABF180_21_R3
FBA status optimal
FBA solution 0.0
EFlux2 status optimal
EFlux2 solution -7.352418252876732e-10
SF ABF180_22_R1
FBA status optimal
FBA solution 0.0
EFlux2 status optimal
EFlux2 solution 1.3398122314101558e-10
SF ABF180_22_R2
FBA status optimal
FBA solution 0.0
EFlux2 status optimal
EFlux2 solution -7.967242923711765e-11
SF ABF180_22_R3
FBA status optimal
FBA solution -1.5347569573252616e-13
EFlux2 status optimal
EFlux2 solution -1.8220620305899195e-09

In [138]:
for rep in global_prot.columns:
    if fluxes[rep].status is not 'optimal':
        print(rep, fluxes[rep].status)

In [142]:
for rep in global_prot.columns:
    print(rep, round(fluxes[rep].objective_value,3))

SF ABF180_1_R1 14.87
SF ABF180_1_R2 14.13
SF ABF180_1_R3 13.752
SF ABF180_2_R1 29.07
SF ABF180_2_R2 25.978
SF ABF180_2_R3 34.923
SF ABF180_3_R1 24.071
SF ABF180_3_R2 27.096
SF ABF180_3_R3 19.801
SF ABF180_4_R1 38.638
SF ABF180_4_R2 24.266
SF ABF180_4_R3 25.665
SF ABF180_5_R1 0.0
SF ABF180_5_R2 0.0
SF ABF180_5_R3 -0.0
SF ABF180_6_R1 14.944
SF ABF180_6_R2 18.595
SF ABF180_6_R3 18.648
SF ABF180_7_R1 18.702
SF ABF180_7_R2 26.328
SF ABF180_7_R3 22.683
SF ABF180_8_R1 20.314
SF ABF180_8_R2 16.595
SF ABF180_8_R3 25.375
SF ABF180_9_R1 32.711
SF ABF180_9_R2 18.063
SF ABF180_9_R3 29.124
SF ABF180_10_R1 20.818
SF ABF180_10_R2 36.134
SF ABF180_10_R3 13.093
SF ABF180_11_R1 29.995
SF ABF180_11_R2 52.29
SF ABF180_11_R3 39.671
SF ABF180_12_R1 51.043
SF ABF180_12_R2 63.796
SF ABF180_12_R3 48.125
SF ABF180_13_R1 31.678
SF ABF180_13_R2 35.07
SF ABF180_13_R3 27.434
SF ABF180_14_R1 34.143
SF ABF180_14_R2 29.919
SF ABF180_14_R3 36.618
SF ABF180_15_R1 31.83
SF ABF180_15_R2 25.637
SF ABF180_15_R3 25.364
SF ABF180_16_R1 33.851
SF ABF180_16_R2 36.258
SF ABF180_16_R3 43.352
SF ABF180_17_R1 -0.0
SF ABF180_17_R2 -0.0
SF ABF180_17_R3 -0.0
SF ABF180_18_R1 45.89
SF ABF180_18_R2 27.094
SF ABF180_18_R3 25.994
SF ABF180_19_R1 -0.0
SF ABF180_19_R2 20.375
SF ABF180_19_R3 -0.0
SF ABF180_20_R1 -0.0
SF ABF180_20_R2 -0.0
SF ABF180_20_R3 40.515
SF ABF180_21_R1 -0.0
SF ABF180_21_R2 -0.0
SF ABF180_21_R3 -0.0
SF ABF180_22_R1 0.0
SF ABF180_22_R2 -0.0
SF ABF180_22_R3 -0.0
SF ABF180_23_R1 37.878
SF ABF180_23_R2 27.809
SF ABF180_23_R3 48.769
SF ABF180_24_R1 31.086
SF ABF180_24_R2 18.224
SF ABF180_24_R3 25.62

### Adding slack variables resulted in zero growth and all-zero fluxes
Adding slack variables to the infeasible subset introduces bias in flux prediction
### Switching to increasing the arbitrary scale for normalized global proteomics

In [68]:
# Find the minimum scaling factor
scaling_factor = 1.0
scaling_finished = False
while not scaling_finished:
    print('scaling_factor:', round(scaling_factor,1))
    scaling_finished = True
    for rep in global_prot.columns:
        if fluxes[rep].status is not 'optimal':
            with model:
                for k, v in const_dict.items():
                    model.reactions.get_by_id(k).lower_bound = normalized_line_rates[v][rep]
                eflux2_bounds = get_eflux2_bounds(model, scaling_factor*global_prot[rep])
                for r in model.reactions:
                    r.bounds = eflux2_bounds[r.id]
                sol = model.optimize()
            print(rep, sol.status, sol.objective_value)
            if sol.status is not 'optimal':
                scaling_factor = scaling_factor + 0.1
                scaling_finished = False
                break
    if scaling_finished:
        print('Done')

scaling_factor: 1.0
SF ABF180_5_R1 infeasible 0.3938817906423824
scaling_factor: 1.1
SF ABF180_5_R1 optimal 2.0200603402074044
SF ABF180_5_R2 optimal 2.4917349909238995
SF ABF180_5_R3 infeasible 0.09162644321819989
scaling_factor: 1.2
SF ABF180_5_R1 optimal 2.7351499012325657
SF ABF180_5_R2 optimal 2.718332096206569
SF ABF180_5_R3 optimal 1.954872291422312
SF ABF180_17_R1 optimal 1.9915037170755006
SF ABF180_17_R2 infeasible 0.19774159602501357
scaling_factor: 1.3
SF ABF180_5_R1 optimal 2.963131064907479
SF ABF180_5_R2 optimal 2.8952887234443914
SF ABF180_5_R3 optimal 2.966833838711774
SF ABF180_17_R1 optimal 1.9915037170755006
SF ABF180_17_R2 optimal 2.1954785455652512
SF ABF180_17_R3 optimal 2.975584320579598
SF ABF180_18_R1 optimal 2.923650686332399
SF ABF180_19_R1 optimal 2.971120656124461
SF ABF180_19_R3 optimal 2.604010639333219
SF ABF180_20_R1 optimal 2.6676393390860946
SF ABF180_20_R2 optimal 2.983070865664022
SF ABF180_20_R3 optimal 2.9798418455564324
SF ABF180_21_R1 optimal 2.641137992853588
SF ABF180_21_R2 optimal 2.966465251943851
SF ABF180_21_R3 optimal 2.9460425344748695
SF ABF180_22_R1 optimal 2.9886638731584583
SF ABF180_22_R2 infeasible 0.08214654169379566
scaling_factor: 1.4
SF ABF180_5_R1 optimal 3.191112228582392
SF ABF180_5_R2 optimal 3.036085085211815
SF ABF180_5_R3 optimal 3.1952659289014598
SF ABF180_17_R1 optimal 1.9915037170755006
SF ABF180_17_R2 optimal 2.1954785455652512
SF ABF180_17_R3 optimal 3.205313128395419
SF ABF180_18_R1 optimal 3.1496409265614607
SF ABF180_19_R1 optimal 3.2007528154161813
SF ABF180_19_R3 optimal 2.604010639333219
SF ABF180_20_R1 optimal 2.6676393390860946
SF ABF180_20_R2 optimal 3.2131261794242283
SF ABF180_20_R3 optimal 3.209784881914898
SF ABF180_21_R1 optimal 2.641137992853588
SF ABF180_21_R2 optimal 3.195360492596791
SF ABF180_21_R3 optimal 3.0239637654832627
SF ABF180_22_R1 optimal 3.2193137571304766
SF ABF180_22_R2 optimal 3.213605779709382
SF ABF180_22_R3 infeasible 0.01684183457604236
scaling_factor: 1.5
SF ABF180_5_R1 optimal 3.3937847244101222
SF ABF180_5_R2 optimal 3.176881446979239
SF ABF180_5_R3 optimal 3.4236980190911463
SF ABF180_17_R1 optimal 1.9915037170755006
SF ABF180_17_R2 optimal 2.1954785455652512
SF ABF180_17_R3 optimal 3.375502231171259
SF ABF180_18_R1 optimal 3.362493558882771
SF ABF180_19_R1 optimal 3.3864631075859495
SF ABF180_19_R3 optimal 2.604010639333219
SF ABF180_20_R1 optimal 2.6676393390860946
SF ABF180_20_R2 optimal 3.4306313154472257
SF ABF180_20_R3 optimal 3.3665799291396246
SF ABF180_21_R1 optimal 2.641137992853588
SF ABF180_21_R2 optimal 3.393201093690104
SF ABF180_21_R3 optimal 3.0239637654832627
SF ABF180_22_R1 optimal 3.3826827160900637
SF ABF180_22_R2 optimal 3.407410469303722
SF ABF180_22_R3 optimal 3.217298036818147
Done

In [69]:
fluxes = {}
scaling_factor = 1.5
for rep in global_prot.columns:
    with model:
        for k, v in const_dict.items():
            model.reactions.get_by_id(k).lower_bound = normalized_line_rates[v][rep]
        try:
            print(rep)
            fluxes[rep] = EFlux2(model, scaling_factor*global_prot[rep])
        except TypeError:
            print(f"Replicate {rep} with glucose {glucose_uptake} and 3hp {secrete_3hp} is infeasible")

SF ABF180_1_R1
FBA status optimal
FBA solution 1.8628795137071203
EFlux2 status optimal
EFlux2 solution 33.80125399895118
SF ABF180_1_R2
FBA status optimal
FBA solution 1.7308518612251669
EFlux2 status optimal
EFlux2 solution 29.1555879190949
SF ABF180_1_R3
FBA status optimal
FBA solution 1.6621861235752382
EFlux2 status optimal
EFlux2 solution 26.891289857622816
SF ABF180_2_R1
FBA status optimal
FBA solution 2.886304110473323
EFlux2 status optimal
EFlux2 solution 81.03362362996859
SF ABF180_2_R2
FBA status optimal
FBA solution 2.8236713462076946
EFlux2 status optimal
EFlux2 solution 77.61952771291868
SF ABF180_2_R3
FBA status optimal
FBA solution 3.098216888489758
EFlux2 status optimal
EFlux2 solution 93.39989996289569
SF ABF180_3_R1
FBA status optimal
FBA solution 2.932254121890804
EFlux2 status optimal
EFlux2 solution 83.63503146717945
SF ABF180_3_R2
FBA status optimal
FBA solution 2.98552737809891
EFlux2 status optimal
EFlux2 solution 86.68033734861231
SF ABF180_3_R3
FBA status optimal
FBA solution 2.7551003581608167
EFlux2 status optimal
EFlux2 solution 73.77634804729595
SF ABF180_4_R1
FBA status optimal
FBA solution 3.3154809937657923
EFlux2 status optimal
EFlux2 solution 117.05777320500836
SF ABF180_4_R2
FBA status optimal
FBA solution 3.051882895948406
EFlux2 status optimal
EFlux2 solution 90.60793021829068
SF ABF180_4_R3
FBA status optimal
FBA solution 3.101942431560871
EFlux2 status optimal
EFlux2 solution 93.38211109039088
SF ABF180_5_R1
FBA status optimal
FBA solution 3.393784724410122
EFlux2 status optimal
EFlux2 solution 128.13249913398272
SF ABF180_5_R2
FBA status optimal
FBA solution 3.1768814469792384
EFlux2 status optimal
EFlux2 solution 100.55510576205921
SF ABF180_5_R3
FBA status optimal
FBA solution 3.4236980190911446
EFlux2 status optimal
EFlux2 solution 131.91800036126523
SF ABF180_6_R1
FBA status optimal
FBA solution 2.266274878286402
EFlux2 status optimal
EFlux2 solution 49.762264446128995
SF ABF180_6_R2
FBA status optimal
FBA solution 2.709314145022352
EFlux2 status optimal
EFlux2 solution 71.03440770499097
SF ABF180_6_R3
FBA status optimal
FBA solution 2.6833816802790946
EFlux2 status optimal
EFlux2 solution 69.7979267049271
SF ABF180_7_R1
FBA status optimal
FBA solution 2.468109446751619
EFlux2 status optimal
EFlux2 solution 59.17701495434292
SF ABF180_7_R2
FBA status optimal
FBA solution 3.0508060364493232
EFlux2 status optimal
EFlux2 solution 90.46597324928237
SF ABF180_7_R3
FBA status optimal
FBA solution 2.811033289741771
EFlux2 status optimal
EFlux2 solution 76.79871656067009
SF ABF180_8_R1
FBA status optimal
FBA solution 2.7941924935139575
EFlux2 status optimal
EFlux2 solution 75.78139224314218
SF ABF180_8_R2
FBA status optimal
FBA solution 2.3652923899440466
EFlux2 status optimal
EFlux2 solution 54.30150473736343
SF ABF180_8_R3
FBA status optimal
FBA solution 2.873921060906701
EFlux2 status optimal
EFlux2 solution 80.84164533727179
SF ABF180_9_R1
FBA status optimal
FBA solution 3.1937387169579594
EFlux2 status optimal
EFlux2 solution 101.93171912617957
SF ABF180_9_R2
FBA status optimal
FBA solution 2.5214998530941175
EFlux2 status optimal
EFlux2 solution 61.63898565447982
SF ABF180_9_R3
FBA status optimal
FBA solution 3.1600193858365655
EFlux2 status optimal
EFlux2 solution 97.76479865112132
SF ABF180_10_R1
FBA status optimal
FBA solution 2.7472017033613563
EFlux2 status optimal
EFlux2 solution 73.27682524831167
SF ABF180_10_R2
FBA status optimal
FBA solution 3.295843946035672
EFlux2 status optimal
EFlux2 solution 113.20126220068364
SF ABF180_10_R3
FBA status optimal
FBA solution 1.682037396556524
EFlux2 status optimal
EFlux2 solution 27.515594284478627
SF ABF180_11_R1
FBA status optimal
FBA solution 3.1373122174915347
EFlux2 status optimal
EFlux2 solution 96.46089342330399
SF ABF180_11_R2
FBA status optimal
FBA solution 3.308742211574231
EFlux2 status optimal
EFlux2 solution 115.23987568577984
SF ABF180_11_R3
FBA status optimal
FBA solution 3.255178716701732
EFlux2 status optimal
EFlux2 solution 107.84000595943618
SF ABF180_12_R1
FBA status optimal
FBA solution 3.3092088496337597
EFlux2 status optimal
EFlux2 solution 115.1507041718497
SF ABF180_12_R2
FBA status optimal
FBA solution 3.376170677000472
EFlux2 status optimal
EFlux2 solution 125.26868005779188
SF ABF180_12_R3
FBA status optimal
FBA solution 3.2506968293963032
EFlux2 status optimal
EFlux2 solution 106.96371306977632
SF ABF180_13_R1
FBA status optimal
FBA solution 3.1879718401028985
EFlux2 status optimal
EFlux2 solution 101.07513438115723
SF ABF180_13_R2
FBA status optimal
FBA solution 3.2233503904180925
EFlux2 status optimal
EFlux2 solution 105.83542237629752
SF ABF180_13_R3
FBA status optimal
FBA solution 2.959938008273229
EFlux2 status optimal
EFlux2 solution 90.27483349095255
SF ABF180_14_R1
FBA status optimal
FBA solution 3.2373451650487137
EFlux2 status optimal
EFlux2 solution 106.74390724034375
SF ABF180_14_R2
FBA status optimal
FBA solution 3.1220462982597423
EFlux2 status optimal
EFlux2 solution 98.73278116474721
SF ABF180_14_R3
FBA status optimal
FBA solution 3.2285842702010283
EFlux2 status optimal
EFlux2 solution 105.23145625211212
SF ABF180_15_R1
FBA status optimal
FBA solution 3.209032403671972
EFlux2 status optimal
EFlux2 solution 103.79688360488612
SF ABF180_15_R2
FBA status optimal
FBA solution 3.1252427232228968
EFlux2 status optimal
EFlux2 solution 94.79827757518675
SF ABF180_15_R3
FBA status optimal
FBA solution 3.0695294008995653
EFlux2 status optimal
EFlux2 solution 90.9550207615124
SF ABF180_16_R1
FBA status optimal
FBA solution 3.2331681406076136
EFlux2 status optimal
EFlux2 solution 105.87049111346383
SF ABF180_16_R2
FBA status optimal
FBA solution 3.2884459396610124
EFlux2 status optimal
EFlux2 solution 114.342857432707
SF ABF180_16_R3
FBA status optimal
FBA solution 3.3387144763319925
EFlux2 status optimal
EFlux2 solution 119.9919589013219
SF ABF180_17_R1
FBA status optimal
FBA solution 1.9915037170755006
EFlux2 status optimal
EFlux2 solution 56.357381954551435
SF ABF180_17_R2
FBA status optimal
FBA solution 2.1954785455652512
EFlux2 status optimal
EFlux2 solution 68.10289379803636
SF ABF180_17_R3
FBA status optimal
FBA solution 3.3755022311712577
EFlux2 status optimal
EFlux2 solution 124.41411187460376
SF ABF180_18_R1
FBA status optimal
FBA solution 3.36249355888277
EFlux2 status optimal
EFlux2 solution 128.17691860248885
SF ABF180_18_R2
FBA status optimal
FBA solution 3.178406061048463
EFlux2 status optimal
EFlux2 solution 98.0255999969345
SF ABF180_18_R3
FBA status optimal
FBA solution 3.1670237626956985
EFlux2 status optimal
EFlux2 solution 96.79584834003036
SF ABF180_19_R1
FBA status optimal
FBA solution 3.3864631075859486
EFlux2 status optimal
EFlux2 solution 126.75253158443601
SF ABF180_19_R2
FBA status optimal
FBA solution 2.840671616719857
EFlux2 status optimal
EFlux2 solution 77.90374414868224
SF ABF180_19_R3
FBA status optimal
FBA solution 2.604010639333219
EFlux2 status optimal
EFlux2 solution 74.24052274504359
SF ABF180_20_R1
FBA status optimal
FBA solution 2.6676393390860946
EFlux2 status optimal
EFlux2 solution 78.1168565596541
SF ABF180_20_R2
FBA status optimal
FBA solution 3.4306313154472243
EFlux2 status optimal
EFlux2 solution 132.31618687717923
SF ABF180_20_R3
FBA status optimal
FBA solution 3.3665799291396237
EFlux2 status optimal
EFlux2 solution 122.77058378142586
SF ABF180_21_R1
FBA status optimal
FBA solution 2.641137992853588
EFlux2 status optimal
EFlux2 solution 78.8538364961006
SF ABF180_21_R2
FBA status optimal
FBA solution 3.393201093690103
EFlux2 status optimal
EFlux2 solution 128.236614586958
SF ABF180_21_R3
FBA status optimal
FBA solution 3.0239637654832627
EFlux2 status optimal
EFlux2 solution 98.61511563413126
SF ABF180_22_R1
FBA status optimal
FBA solution 3.3826827160900637
EFlux2 status optimal
EFlux2 solution 124.41236432116585
SF ABF180_22_R2
FBA status optimal
FBA solution 3.407410469303722
EFlux2 status optimal
EFlux2 solution 128.22653073429336
SF ABF180_22_R3
FBA status optimal
FBA solution 3.217298036818147
EFlux2 status optimal
EFlux2 solution 118.54277560581272
SF ABF180_23_R1
FBA status optimal
FBA solution 3.1803433043538476
EFlux2 status optimal
EFlux2 solution 98.23100182543726
SF ABF180_23_R2

FBA status optimal
FBA solution 3.0086128821130638
EFlux2 status optimal
EFlux2 solution 87.82890936373508
SF ABF180_23_R3
FBA status optimal
FBA solution 3.2539768009047583
EFlux2 status optimal
EFlux2 solution 108.75154102732135
SF ABF180_24_R1
FBA status optimal
FBA solution 3.236020821638173
EFlux2 status optimal
EFlux2 solution 106.18375082615182
SF ABF180_24_R2
FBA status optimal
FBA solution 2.4425435977161407
EFlux2 status optimal
EFlux2 solution 57.493308750321276
SF ABF180_24_R3
FBA status optimal
FBA solution 3.1543803086731343
EFlux2 status optimal
EFlux2 solution 96.38298277293649

In [70]:
for rep in global_prot.columns:
    if fluxes[rep].status is not 'optimal':
        print(rep, fluxes[rep].status)

In [72]:
eflux_rates = pd.DataFrame(dict([(rep, fluxes[rep].to_frame()['fluxes']) for rep in fluxes]))
eflux_rates.head()

,SF ABF180_1_R1,SF ABF180_1_R2,SF ABF180_1_R3,SF ABF180_2_R1,SF ABF180_2_R2,SF ABF180_2_R3,SF ABF180_3_R1,SF ABF180_3_R2,SF ABF180_3_R3,SF ABF180_4_R1,...,SF ABF180_21_R3,SF ABF180_22_R1,SF ABF180_22_R2,SF ABF180_22_R3,SF ABF180_23_R1,SF ABF180_23_R2,SF ABF180_23_R3,SF ABF180_24_R1,SF ABF180_24_R2,SF ABF180_24_R3
r5a,0.609345,0.566700,0.544114,0.944467,0.922727,1.013443,0.961490,0.979892,0.905427,1.199513,...,1.119526,1.257292,1.290709,1.252386,1.044309,0.989133,1.137562,1.124896,0.812758,1.040476
r10,0.306548,0.284844,0.273534,0.474772,0.464352,0.509618,0.482778,0.491707,0.453913,0.628005,...,0.586642,0.661700,0.681823,0.670494,0.523663,0.495416,0.586476,0.575134,0.403212,0.519815
r12a,0.306548,0.284844,0.273534,0.474772,0.464352,0.509618,0.482778,0.491707,0.453913,0.628005,...,0.586642,0.661700,0.681823,0.670494,0.523663,0.495416,0.586476,0.575134,0.403212,0.519815
r13a,0.306548,0.284844,0.273534,0.474772,0.464352,0.509618,0.482778,0.491707,0.453913,0.628005,...,0.586642,0.661700,0.681823,0.670494,0.523663,0.495416,0.586476,0.575134,0.403212,0.519815
r14,0.616847,0.572676,0.550021,0.954621,0.934682,1.025027,0.969622,0.986936,0.910224,1.312508,...,1.227040,1.389506,1.436581,1.429589,1.050341,0.992532,1.208343,1.175638,0.800091,1.038784

In [54]:
#eflux_rates.to_csv('../../data/round2/Eflux2_flux_rates_raw.csv')

In [73]:
eflux_rates = eflux_rates*ref_line_glucose_rate
eflux_rates.head()

,SF ABF180_1_R1,SF ABF180_1_R2,SF ABF180_1_R3,SF ABF180_2_R1,SF ABF180_2_R2,SF ABF180_2_R3,SF ABF180_3_R1,SF ABF180_3_R2,SF ABF180_3_R3,SF ABF180_4_R1,...,SF ABF180_21_R3,SF ABF180_22_R1,SF ABF180_22_R2,SF ABF180_22_R3,SF ABF180_23_R1,SF ABF180_23_R2,SF ABF180_23_R3,SF ABF180_24_R1,SF ABF180_24_R2,SF ABF180_24_R3
r5a,3.824936,3.557249,3.415471,5.928543,5.792077,6.361510,6.035393,6.150907,5.683483,7.529497,...,7.027410,7.892183,8.101947,7.861385,6.555260,6.208917,7.140623,7.061118,5.101785,6.531200
r10,1.924241,1.788003,1.717006,2.980206,2.914799,3.198934,3.030459,3.086508,2.849269,3.942069,...,3.682424,4.153573,4.279888,4.208774,3.287097,3.109792,3.681386,3.610186,2.531015,3.262944
r12a,1.924241,1.788003,1.717006,2.980206,2.914799,3.198934,3.030459,3.086508,2.849269,3.942069,...,3.682424,4.153573,4.279888,4.208774,3.287097,3.109792,3.681386,3.610186,2.531015,3.262944
r13a,1.924241,1.788003,1.717006,2.980206,2.914799,3.198934,3.030459,3.086508,2.849269,3.942069,...,3.682424,4.153573,4.279888,4.208774,3.287097,3.109792,3.681386,3.610186,2.531015,3.262944
r14,3.872027,3.594763,3.452554,5.992279,5.867121,6.434227,6.086442,6.195123,5.713593,8.238780,...,7.702288,8.722107,9.017603,8.973711,6.593127,6.230251,7.584920,7.379628,5.022274,6.520578

## Process eflux_rates and reduce metabolic model

In [80]:
eflux_rates[abs(eflux_rates) < 1e-8] = 0.0

In [81]:
print('number of reactions', len(eflux_rates))
print('all zero flux', len(eflux_rates[(abs(eflux_rates) == 0).all(axis=1)]))
print('non-zero flux', len(eflux_rates[(abs(eflux_rates) != 0).any(axis=1)]))

number of reactions 93
all zero flux 0
non-zero flux 93

In [82]:
# remove reactions with all zero flux
reduced_model = model.copy()
zero_flux = eflux_rates.index[(abs(eflux_rates) == 0).all(axis=1)]
reduced_model.remove_reactions(zero_flux, remove_orphans=True)
eflux_rates.drop(zero_flux, inplace=True)

In [83]:
print('non-zero', len(eflux_rates))
print('non-negative', len(eflux_rates[(eflux_rates >= 0).all(axis=1)]))
print('non-positive', len(eflux_rates[(eflux_rates <= 0).all(axis=1)]))
print('mixed sign', len(eflux_rates[(eflux_rates > 0).any(axis=1) & (eflux_rates < 0).any(axis=1)]))

non-zero 93
non-negative 75
non-positive 17
mixed sign 1

In [84]:
# Update the lower bound of reactions with non-negative flux
for x in eflux_rates.index[(eflux_rates >= 0).all(axis=1)]:
    r = reduced_model.reactions.get_by_id(x)
    r.lower_bound = 0.0

In [85]:
# Reverse reactions with non-positive flux
for x in eflux_rates.index[(eflux_rates <= 0).all(axis=1)]:
    r = reduced_model.reactions.get_by_id(x)
    r.id = r.id + 'r'
    r.lower_bound = 0.0
    for m, s in r.metabolites.items():
        r.add_metabolites({m: -2*s})
    eflux_rates.loc[x] = -eflux_rates.loc[x]
    eflux_rates.rename(index={x: x+'r'}, inplace=True)

In [86]:
# Split reactions with mixed signs
for x in eflux_rates.index[(eflux_rates > 0).any(axis=1) & (eflux_rates < 0).any(axis=1)]:
    r = reduced_model.reactions.get_by_id(x)
    r.lower_bound = 0.0
    r_reverse = r.copy()
    r_reverse.id = r.id+'r'
    reduced_model.add_reactions([r_reverse])
    for m, s in r_reverse.metabolites.items():
        r_reverse.add_metabolites({m: -2*s})
    eflux_rates.loc[x+'r'] = -eflux_rates.loc[x]
    eflux_rates.loc[x][eflux_rates.loc[x] < 0] = 0.0
    eflux_rates.loc[x+'r'][eflux_rates.loc[x+'r'] < 0] = 0.0

In [87]:
for r in reduced_model.reactions:
    if r.lower_bound < 0.0:
        print(r)

In [88]:
print('reduced', len(eflux_rates))
print('non-negative', len(eflux_rates[(eflux_rates >= 0).all(axis=1)]))
print('non-positive', len(eflux_rates[(eflux_rates <= 0).all(axis=1)]))
print('mixed sign', len(eflux_rates[(eflux_rates > 0).any(axis=1) & (eflux_rates < 0).any(axis=1)]))

reduced 94
non-negative 94
non-positive 0
mixed sign 0

In [89]:
# Check reactions with zero flux in the reference strain
eflux_rates[eflux_rates[ref_line] == 0]

,SF ABF180_1_R1,SF ABF180_1_R2,SF ABF180_1_R3,SF ABF180_2_R1,SF ABF180_2_R2,SF ABF180_2_R3,SF ABF180_3_R1,SF ABF180_3_R2,SF ABF180_3_R3,SF ABF180_4_R1,...,SF ABF180_21_R3,SF ABF180_22_R1,SF ABF180_22_R2,SF ABF180_22_R3,SF ABF180_23_R1,SF ABF180_23_R2,SF ABF180_23_R3,SF ABF180_24_R1,SF ABF180_24_R2,SF ABF180_24_R3
r28r,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.039755,0.005311

### Handle the reactions with zero flux in the reference strain

In [119]:
ref_zero_flux = eflux_rates.index[eflux_rates[ref_line] == 0]
eflux_rates.loc[ref_zero_flux][eflux_rates.loc[ref_zero_flux] > 0].min(axis=1)

r28r    0.005311
dtype: float64

In [117]:
# r28 and r28r can cancel out if adding the same value
eflux_rates[ref_line]['r28']

0.7959490545709038

In [116]:
# Calculate the maximum fold change in other reactions
temp = eflux_rates.divide(eflux_rates[ref_line], axis=0).max(axis=1)
temp[temp < np.inf].max()

5.313918048379364

In [120]:
# Adding 1e-3 to r28 and r28r in the reference strain, resulting in > 5 fold change
eflux_rates[ref_line]['r28'] = eflux_rates[ref_line]['r28'] + 0.001
eflux_rates[ref_line]['r28r'] = eflux_rates[ref_line]['r28r'] + 0.001

In [121]:
for x in ref_zero_flux:
    r = reduced_model.reactions.get_by_id(x)
    print(r)

r28r: F6P + T3P1 --> E4P + XUL5P

In [124]:
for k in eflux_rates:
    print(k)
    for m in reduced_model.metabolites:
        temp = 0
        for r in m.reactions:
            temp = temp + r.get_coefficient(m)*eflux_rates[k][r.id]
        if abs(temp) > 1e-9:
            print(m.id, temp)

SF ABF180_1_R1
SF ABF180_1_R2
SF ABF180_1_R3
SF ABF180_2_R1
SF ABF180_2_R2
SF ABF180_2_R3
SF ABF180_3_R1
SF ABF180_3_R2
SF ABF180_3_R3
SF ABF180_4_R1
SF ABF180_4_R2
SF ABF180_4_R3
SF ABF180_5_R1
SF ABF180_5_R2
SF ABF180_5_R3
SF ABF180_6_R1
SF ABF180_6_R2
SF ABF180_6_R3
SF ABF180_7_R1
SF ABF180_7_R2
SF ABF180_7_R3
SF ABF180_8_R1
SF ABF180_8_R2
SF ABF180_8_R3
SF ABF180_9_R1
SF ABF180_9_R2
SF ABF180_9_R3
SF ABF180_10_R1
SF ABF180_10_R2
SF ABF180_10_R3
SF ABF180_11_R1
SF ABF180_11_R2
SF ABF180_11_R3
SF ABF180_12_R1
SF ABF180_12_R2
SF ABF180_12_R3
SF ABF180_13_R1
SF ABF180_13_R2
SF ABF180_13_R3
SF ABF180_14_R1
SF ABF180_14_R2
SF ABF180_14_R3
SF ABF180_15_R1
SF ABF180_15_R2
SF ABF180_15_R3
SF ABF180_16_R1
SF ABF180_16_R2
SF ABF180_16_R3
SF ABF180_17_R1
SF ABF180_17_R2
SF ABF180_17_R3
SF ABF180_18_R1
SF ABF180_18_R2
SF ABF180_18_R3
SF ABF180_19_R1
SF ABF180_19_R2
SF ABF180_19_R3
SF ABF180_20_R1
SF ABF180_20_R2
SF ABF180_20_R3
SF ABF180_21_R1
SF ABF180_21_R2
SF ABF180_21_R3
SF ABF180_22_R1
SF ABF180_22_R2
SF ABF180_22_R3
SF ABF180_23_R1
SF ABF180_23_R2
SF ABF180_23_R3
SF ABF180_24_R1
SF ABF180_24_R2
SF ABF180_24_R3

## Save eflux rates and reduced metabolic model

In [125]:
eflux_rates.to_csv('../../data/round2/Eflux2_flux_rates_reduced_before_eflux.csv')

In [126]:
cobra.io.save_json_model(reduced_model, '../../models/iJB1325_HP_reduced_before_eflux_round2.json')